# serverless.yml

service: engenhos-it-cidade-verde

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  tableNameFeed: 'feed-table-${self:provider.stage}-${self:provider.environment.BUILD_NUMBER}'
  dynamodb:
    start:
      migrate: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - { "Fn::GetAtt": ["FeedDynamoDBTable", "Arn" ] }
  environment:
    BUILD_NUMBER: '0.0.3'
    FEED_TABLE: ${self:custom.tableNameFeed}

functions:  
  getFeed:
    handler: index.handler
    events:
      - http: 'GET /feed'
  createFeed:
    handler: index.handler
    events:
      - http: 'POST /feed'
      - schedule: 
         name: cidade-verde-update-feed
         rate: rate(3 hours)

resources:
  Resources:
    FeedDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: guid
            AttributeType: S
        KeySchema:
          - AttributeName: guid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableNameFeed}